<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Betalgo.Ranul.OpenAI" Version="9.2.6" />
    <PackageReference Include="Mindee" Version="3.39.0" />
    <PackageReference Include="QuestPDF" Version="2025.5.1" />
    <PackageReference Include="Telegram.Bot" Version="22.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TelegramBot.Application\TelegramBot.Application.csproj" />
    <ProjectReference Include="..\TelegramBot.Domain\TelegramBot.Domain.csproj" />
    <ProjectReference Include="..\TelegramBot.SharedKernel\TelegramBot.SharedKernel.csproj" />
  </ItemGroup>

</Project>
