<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>db6c9fbe-af31-4379-bb1a-55f7a17088cc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TelegramBot.Application\TelegramBot.Application.csproj" />
    <ProjectReference Include="..\TelegramBot.Domain\TelegramBot.Domain.csproj" />
    <ProjectReference Include="..\TelegramBot.Infrastructure\TelegramBot.Infrastructure.csproj" />
    <ProjectReference Include="..\TelegramBot.SharedKernel\TelegramBot.SharedKernel.csproj" />
  </ItemGroup>

</Project>
